# https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages
arb-dir: lib/resources/l10n
template-arb-file: intl_en.arb
output-class: S
